import "./global.css";
import { CopilotProvider } from "./features/chat/copilot_provider";

export const metadata = {
  title: "Welcome to ",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CopilotProvider>{children}</CopilotProvider>
      </body>
    </html>
  );
}
