import "./global.css";
import { CopilotKit } from "@copilotkit/react-core/v2";
import "@copilotkit/react-core/v2/styles.css";

const runtimeUrl =
  process.env.NEXT_PUBLIC_COPILOTKIT_RUNTIME_URL ?? "/api/copilotkit";

export const metadata = {
  title: "Welcome to ",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CopilotKit runtimeUrl={runtimeUrl}>
        <body>{children}</body>
      </CopilotKit>
    </html>
  );
}
