# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "clients.baml": "// \"openai-generic\" (not \"openai\") is BAML's documented provider for\n// OpenAI-compatible local servers like LM Studio/Ollama. env.VAR\n// interpolation keeps this pointed at whatever the app's LLM_BASE_URL/\n// LLM_API_KEY/LLM_MODEL settings resolve to - nothing hardcoded here.\nclient<llm> LocalGemma {\n  provider openai-generic\n  options {\n    base_url env.LLM_BASE_URL\n    api_key env.LLM_API_KEY\n    model env.LLM_MODEL\n  }\n}\n",
    "generators.baml": "// Generated client lands inside the `pythonapi` package (not at the repo\n// root or app root) so hatchling's `packages = [\"pythonapi\"]` picks it up\n// for the built wheel. Re-run `uv run baml-cli generate` from\n// apps/pythonapi/ after editing any .baml file, and commit the output.\ngenerator target {\n  output_type \"python/pydantic\"\n  // BAML appends a \"baml_client\" package dir beneath output_dir, so this\n  // resolves to apps/pythonapi/pythonapi/baml_client/ - inside the\n  // `pythonapi` package that hatchling picks up for the built wheel.\n  output_dir \"../pythonapi\"\n\n  // Must track the installed baml-py version (see pyproject.toml/uv.lock) -\n  // baml-cli generate errors on a mismatch.\n  version \"0.225.0\"\n\n  // core/generation.py imports from baml_client.async_client explicitly,\n  // so this only affects what the bare `b` shortcut resolves to.\n  default_client_mode async\n}\n",
    "rag.baml": "class RAGAnswer {\n  is_answerable bool @description(\"True if the provided context explicitly contains the answer.\")\n  answer string @description(\"The final answer. If is_answerable is false, explain why.\")\n  confidence float @description(\"A confidence score between 0.0 and 1.0\")\n}\n\nfunction GenerateAnswer(context: string, question: string) -> RAGAnswer {\n  client LocalGemma\n  prompt #\"\n    You are an expert analytical assistant.\n    Answer the user's question based strictly on the following context.\n\n    The context may contain redacted placeholder tokens shaped like\n    <PERSON_a1b2c3d4> in place of real names, emails, phone numbers, or\n    other personal data. Treat each token as an opaque identifier for a\n    specific (unknown) entity - reuse it verbatim in your answer exactly as\n    written wherever it refers to that entity, and never attempt to guess\n    or invent the real value it stands for.\n\n    Context:\n    {{ context }}\n\n    Question:\n    {{ question }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
}

def get_baml_files():
    return _file_map